### ISSUE TITLE
Allow auto-closing unsigned commits from committers who volunteer for it

### ISSUE THREAD

**Issue by hexylena** [erasche/p4#13]

**Comment by martenson** [comment]
I can be the bot for you here. :D

**Comment by martenson** [comment]
this feels too strict, feel free to make jenkins do it but it shouldn't probably ever be part of our `official p4 bot`! :)

**Comment by hexylena** [comment]
@martenson I think it was you who originally suggested this ;P

**Comment by martenson** [comment]
@erasche Well I am signing now too, we can keep an eye on each other's signature :P
