### ISSUE TITLE
make p4 add popularity to issues of any age

### ISSUE THREAD

**Issue by martenson** [erasche/p4#18]

**Comment by hexylena** [comment]
This should be happening, assuming +1s are being counted correctly.

**Comment by martenson** [comment]
this does not work, there are no popularity tags being added by galaxybot to issues (only prs)

**Comment by hexylena** [comment]
:(

**Comment by hexylena** [comment]
https://github.com/galaxyproject/galaxy/pull/1899 ?

**Comment by hexylena** [comment]
(Can't count the on-comment votes until later)

**Comment by hexylena** [comment]
Okay, I've found counter-examples. Will debug.

**Comment by martenson** [comment]
@erasche that is a pull request, I am talking about issues

**Comment by hexylena** [comment]
@martenson aha.

**Comment by nsoranzo** [comment]
Both @dannon and me would like the popularity labels added only to issues, not PRs. Not sure about other people.

**Comment by dannon** [comment]
Yep!

**Comment by hexylena** [comment]
Sure. Whenever p4 supports issues (instead of just PRs) we can make that change.

**Comment by martenson** [comment]
Looking back this seems like an overkill given we have reaction sorting in GH interface. Closing.

**Comment by hexylena** [comment]
Huh, that's new. Neat.
