### ISSUE TITLE
make p4 understand the new :+1: attached to comments

### ISSUE THREAD

**Issue by martenson** [erasche/p4#19]

**Comment by hexylena** [comment]
I'm not seeing this exposed in the API
https://api.github.com/repos/galaxyproject/p4/issues/19

**Comment by hexylena** [comment]
https://developer.github.com/changes/2016-05-12-reactions-api-preview/ right.

**Comment by nsoranzo** [comment]
I think that it's more important that p4 understand the newer "Approve review" GitHub feature.

**Comment by hexylena** [comment]
+1

Den tor. 1. des. 2016, 19.47 skrev Nicola Soranzo <notifications@github.com

**Comment by martenson** [comment]
github now has sorting of issues based on number of reactions, that suffices our purpose I think, closing
